---
title: "MATH 216 Homework 5"
author: "Paul Suberu"
output: html_document
---

```{ r, echo=FALSE, message=FALSE, fig.width=12, fig.height=6}
library(dplyr)
library(stringr)
library(tm)
library(wordcloud)
library(SnowballC)
library(tidyr)
library(shiny)
library(ggplot2)
library(ggthemes)
```


## Admistrative:

Please indicate

* Who you collaborated with:
* Roughly how much time you spent on this HW:4
* What gave you the most trouble:Getting the Shiny app to work
* Any comments you have: 





## Question 1:

* Pick three books from [Project Gutenberg](https://www.gutenberg.org/) and make
a "single-file" Shiny app based on file `App.R`
    + showing the corresponding wordcloud for a given book
    + that has "toggle" functionality to switch between the three books
* Note: Project Gutenberg tends to have older books whose copyright has expired.
* Install all necessary packages on your Middlebury Shiny server account
following the instructions given in Lec16 Shiny.
* Upload your app to the Middlebury Shiny server and replace the NHL link with
the link for your app [here](https://www.nhl.com/), so that when you Knit the 
document a working hyperlink shows.

Hints:

* Get your code completely working for a non-Shiny app first, then build your
app slowly.
* If you get stuck, please ask for help sooner rather than later. I don't want 
people spinning their wheels on this HW this late in the semester.
* Consider using `if` and `else` statements to switch out which text to show the
wordcloud for. Note this isn't the only way to do this. Ex:

```{r, echo=FALSE, message=FALSE, fig.width=12, fig.height=6}
text <- "blah2"
if(text == "blah1"){
  value <- 1
} else if (text == "blah2"){
  value <- 2
} else if (text == "blah3"){
  value <- 3
}
value

EllenLevis <-readLines("EllenLevis.txt", encoding="UTF-8") %>%
as.character()

Dawn <-readLines("DawnOfHistory.txt", encoding="UTF-8") %>%
as.character()

Witchcraft<-readLines("TheWitchcraftDelusion.txt", encoding="UTF-8") %>%
as.character()


EllenLevis <- EllenLevis %>%
tolower() %>%
removeNumbers() %>%
removePunctuation() %>%
removeWords(stopwords("english")) %>%
stemDocument() %>%
stripWhitespace()


Dawn<- Dawn %>%
tolower() %>%
removeNumbers() %>%
removePunctuation() %>%
removeWords(stopwords("english")) %>%
stemDocument() %>%
stripWhitespace()
 

Witchcraft <- Witchcraft %>%
tolower() %>%
removeNumbers() %>%
removePunctuation() %>%
removeWords(stopwords("english")) %>%
stemDocument() %>%
stripWhitespace()


EllenLevis <- VectorSource(EllenLevis) %>% Corpus()
wordcloud(EllenLevis, scale=c(5,0.5), max.words=25, random.order=FALSE,
rot.per=0.35, use.r.layout=FALSE, colors=brewer.pal(8, "BuPu"))


Dawn <- VectorSource(Dawn) %>% Corpus()
wordcloud(Dawn, scale=c(5,0.5), max.words=25, random.order=FALSE,
rot.per=0.35, use.r.layout=FALSE, colors=brewer.pal(8, "BuPu"))


Witchcraft <- VectorSource(Witchcraft) %>% Corpus()
wordcloud(Witchcraft, scale=c(5,0.5), max.words=25, random.order=FALSE,
rot.per=0.35, use.r.layout=FALSE, colors=brewer.pal(8, "BuPu"))


ui <- shinyUI(fluidPage(
titlePanel("Book Word Clouds"),
sidebarLayout(
sidebarPanel(
selectInput("selection", "Choose a book:",
choices = c("Dawn", "EllenLevis", "Witchcraft"))
),
mainPanel(
plotOutput("distPlot")
)
)
))

server <- shinyServer(function(input, output) {
output$distPlot <- renderPlot({
x <- faithful[, 2] 
#bins <- seq(min(x), max(x), length.out = input$bins + 1)
bins <- seq(min(x), max(x), length.out = 1)
hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
})
shinyApp(ui = ui, server = server)
library(rsconnect)
rsconnect::deployApp('path/to/your/app')
```

